name = "p2p-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# [[routes]]
# pattern = "api.ethsltd.com"
# custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "ethsltd_db"
database_id = "3e91dec1-5e94-434a-9697-7a9217592afe"
migrations_dir = "../../database/migrations"

# [[r2_buckets]]
# binding = "R2_BACKUPS"
# bucket_name = "ethsltd-backups"

[vars]
CREGIS_PROXY_URL = "https://techilyfly.com/ethsltd/cregis-proxy.php"
CREGIS_PROXY_SECRET = "ETHSLTD_CREGIS_PROXY_SECURE_TOKEN_2026"
