name = "p2p-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "p2p_ethsltd_isolated_db"
database_id = "73501363-745e-4e12-9442-38c6b2af6f4c"
migrations_dir = "../../database/migrations"

# [[r2_buckets]]
# binding = "R2_BACKUPS"
# bucket_name = "ethsltd-backups"

[vars]
CREGIS_PROXY_URL = "https://techilyfly.com/ethsltd/cregis-proxy.php"
CREGIS_PROXY_SECRET = "ETHSLTD_CREGIS_PROXY_SECURE_TOKEN_2026"
